<?php

namespace Database\Seeders;

use App\Models\CataloguesAndEbooks;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CatalogueSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $catalogues = [
            [
                'title' => 'COVET HOUSE CASEGOODS',
                'subtitle' => null,
                'description' => 'From contemporary, to modern and classic. In The Ultimate Casegoods Catalogue there is an extensive array of collections, mirrors, sideboards, and armoirs. Curated design, Inspiration, and craftsmanship are some of the main ingredients of the pieces you can find inside. Download this catalogue and find the Key piece you’ve been missing in your home decor.',
                'type' => 'catalogue',
                'slug' => 'covet-house-casegoods',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'COVET HOUSE SEATING',
                'subtitle' => null,
                'description' => 'Discover the most coveted selection of seating furniture. In this catalogue you can count on a refined selection of sofas, armchairs, dining chairs, and counter stools (among many others). With all the technical information you need, this catalogue offers the widest selection of curated seating products. Download this catalogue and discover more!',
                'type' => 'catalogue',
                'slug' => 'covet-house-seating',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Hospitality Projects',
                'subtitle' => null,
                'description' => 'After a strict pause in 2020, the hospitality industry is back in the game with renewed attention to sustainability and well-being. Since last year, the world has been presented with exceptional new Hotels, Restaurants and Spa projects around the world that have redefined Guest Experience with new strategies. Striking interiors with authentic character play a differentiating role in this new era of Hospitality Design, as does the reinvention of spaces to suit the modern lifestyle, and integrating local experiences to allow trav- elers to truly connect with the destination.As the industry is experiencing a revival, inspiration is key. Covet House presents a collection of design-led hotels, restaurants and Spas that function both as social hubs and platforms for extraordinary expe- riences. We present this series of 200 carefully curated Hospitality Interiors that provide an individualized look at the modern hospitality narrative. This book explores in detail the new hospitality interior design trends that launch the pillars of a Changing World and sets itself as a source of inspiration for Interior Designers by exploring different styles and concepts. Join us in this new Design Experience!',
                'type' => 'catalogue',
                'slug' => 'inspirations-hospitality-projects',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'COVET HOUSE BATHROOM',
                'subtitle' => 'Discover the Most Coveted Designs for Bathrooms',
                'description' => 'Beautiful use of space. We believe that bathrooms are more than just functional spaces. The Ultimate Bathroom Catalogue, an exquisite catalogue with inspirations, illustrated products, and technical information, offers a wide selection of basins and vanities, as well as a range of accessories to dress the perfect bathroom. Download this catalogue and discover more!',
                'type' => 'catalogue',
                'slug' => 'covet-house-bathroom',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'COVET HOUSE LIGHTING',
                'subtitle' => 'Discover the Most Coveted Designs for Lighting',
                'description' => 'The Lighting Catalogue offers you a curated and refined selection of the best lamps. From modern to classic to mid-century, in this new catalogue you can see the different colors, materials, finishes, and categories. Featuring all the technical information needed to create every type of interior design project this catalogue is the ultimate tool you need to light up your projects. Download this catalogue and discover more!',
                'type' => 'catalogue',
                'slug' => 'covet-house-lighting',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Dining Rooms',
                'subtitle' => 'TASTEFULLY DECORATED, THESE ARE THE IDEAS THAT WILL SATISFY YOUR HUNGER FOR INSPIRATION.',
                'description' => 'Luxury design as always sparked hundreds of people’s imaginations. It has been seen by many as the zenith of lifestyle, the way to be and to live. What better way to commemorate life than a grandiose and lavish dinner party? Surrounded by family and friends, all of this is enveloped by the most taste- ful and exquisite ambiance and decoration. Decorating your dining room with beautiful upholstery, lighting, and accessories is a symbol of class and elegance. With these inspirations, we made sure you get a bit of everything from mid-century to contemporary but the real goal here is to combine styles and get a curated look that feels authentic and genuine to please everyone’s taste. Dining rooms are also synonymous with luxury restaurants, chic fashion statements, inspiring portraits, beautiful architecture, and, of course, glam- orous interior design. Sophistication is key here, bringing up the process of beautifying the dining rooms with a natural instinctive capacity to come up with magnificence and effectively amalgamate the old with the new, fabrics and textiles, materials, and finishes. Achieving a curated look is less chal- lenging than you may think, especially with all the tasteful tips and looks.',
                'type' => 'catalogue',
                'slug' => 'inspirations-dining-rooms',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Entryways',
                'subtitle' => 'DESIGNS FOR AN EVERLASTING FIRST IMPRESSION',
                'description' => 'Welcoming you into the house is a splendorous sight, a foyer or entrance that will set the tone for the rest of your home. No matter the size, you won’t get a second chance of causing a good first impression, so, although this room is most of the time dismissive or underplayed, it is one of the most important areas in a house. Focused on blending different styles under the same space, these ambiances will brings light and give you some inspiration when creating your dream entryway. A combination of materials, finishes, colors and styles ultimately provides a richer aesthetic to a room that can be sometimes overlooked. Covet House is always on an everlasting ride to provide you with unique luxury furniture ideas and to show you how powerful curated design can be, from the widest foyer to a simple corridor, no detail is misplaced or forgotten in these entryway inspirations.',
                'type' => 'catalogue',
                'slug' => 'inspirations-entryways',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Kids',
                'subtitle' => 'FUN, DREAMFUL AND SOOTHING AMBIANCES FOR THE LITTLE ONES',
                'description' => 'What was the layout of your room when you were a kid? We’re guessing not like these vibrant, inventive, and obviously amazing settings. These uber trendy kids’ bedrooms are lessons in strategic editing, creative ideas, and extremely good taste. Discover new inspiration every day and explore the best way to bring that inspiration to life. Kids and their adventurous minds are the biggest inspiration, they have very specific visions of how they want to decorate their bedrooms, and those ideas are also often inspired by epic movie sets and elaborate fairy tales backdrops. It just takes a balance of childlike imagination with adult practicality and style, and these ambiances are the perfect example of how to achieve such a fun balance.',
                'type' => 'catalogue',
                'slug' => 'inspirations-kids',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Bathrooms',
                'subtitle' => 'Discover the Most Coveted Designs for Bathrooms',
                'description' => 'The bathroom is as significant as any other area in your home since it is where you begin and end each day. Yet, all too frequently, it feels out of place with the rest of the house, imbued with less love and individuality. And the expectations we place on them, such as water-friendly surfaces and bright, IP-rated lighting, can result in a chilly, unattractive environment. Lighting, texture, and color are all factors to consider when designing a bathroom and don’t forget to include anything that piques your imagination and elevates your mood. Above all, a bathroom must be clean and neat. But it doesn’t have to be strictly functional, especially if you enjoy bubble baths or mirror selfies. We’ve gathered a bunch of bathroom ideas to help you create an oasis for spa-level relaxation and style in your own house to inspire some creativity. Whether you’re thinking of cleaning up the powder room and main bath, or going on a full-on ensuite renovation, we’ve got the right inspiration to take your bathroom to your aspirations.',
                'type' => 'catalogue',
                'slug' => 'inspirations-bathrooms',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Offices',
                'subtitle' => 'Discover the Most Coveted Designs for Offices',
                'description' => 'Home offices have never been more relevant, we really think it is more than fundamental to have a peaceful environment while working and still make it in style. Almost everyone needs to bring work home with them at some point, whether it’s a stack of paperwork or something saved on a laptop. If you are not an office worker, you may want a separate space to go through domestic bills and communications. Even children require a place to sit and concentrate on homework or computer research. Whatever your demands are, chances are you’ll need a home office – whether that’s a full-fledged room, a corner, or a pull-out shelf. This series of home offices in which we focus on luxury design, where the division gets more inviting and exclusive, perfect to feel powerful and work on your next projects.',
                'type' => 'catalogue',
                'slug' => 'inspirations-offices',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Inspirations Bedrooms',
                'subtitle' => 'Discover the Most Coveted Designs for Bedrooms',
                'description' => 'The bedroom is probably, the most important place when it comes to your home design. It’s your safe place, a retreat from the world, and a place for a relaxing and soothing time. Whether you dream of a calm and restful sanctuary or a luxurious hotel-style bedroom, our inspirations for bedroom ideas are all you need to know before you make a start, from finding the perfect mattress to choosing a bedroom color scheme. Wrap your sleepy eyes around this gallery of energizing modern bedroom designs and stunning bedroom accessories that will wake you up. There is something here for everyone, from ultra-sleek minimalist design bedrooms to warm modern rustic décor schemes, from crisp contemporary style to a cacophony of colorful possibilities. Discover incredibly innovative headboard feature wall designs that integrate extruded panels and headboards, minimalistic bedside units, drawers and shelves, and gorgeous closets to hold your very own daily catwalk collection to dress for success in the morning. Interiors are all about you and being one with the space itself, so get ready for exclusive atmospheres, contemporary elements, and luxurious details.',
                'type' => 'catalogue',
                'slug' => 'inspirations-bedrooms',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'COVET HOUSE TABLES',
                'subtitle' => 'Discover the Most Coveted Designs for Tables',
                'description' => 'Take a look at our new catalogue dedicated to our extensive Tables collection. Choose from contemporary to modern coffee and dining tables, bedsides, and desks. Download now and discover our extended catalogue of luxury tables, pick the ideal idea for your design project, and enjoy the inspiration our furniture can provide you. Download this catalogue and discover more!',
                'type' => 'catalogue',
                'slug' => 'covet-house-tables',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Covet House Beds',
                'subtitle' => 'Discover the Most Coveted Designs for Beds',
                'description' => 'Choosing a statement bed with distinctive shapes, intricate details, or interesting textures is an excellent way to make a bold and stylish statement in your bedroom. The first thing to do is to consider the size of the bed in relation to the bedroom space. A statement bed should be proportionate to the room, not overwhelming or too small to have the desired impact, and made from high-quality materials such as wood, metal, upholstered fabric, or a combination of materials for a more eclectic look. The headboard is often the focal point of a statement bed, that is why we present a set of elaborate and artistic headboard designs that catch the eye in the next pages. Remember that a statement bed should reflect one’s personality and style while also fitting harmoniously into the overall design of the bedroom.',
                'type' => 'catalogue',
                'slug' => 'covet-house-beds',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Covet House Kids',
                'subtitle' => 'Discover the Most Coveted Designs for Kids',
                'description' => 'To create a vibrant and functional kids’ room design that brings joy and creativity into the child’s living space, one must create a magical world. daunting as it may seem, you just need good inspiration. In the next pages, you will find a theme for virtually every kid’s dream, from space to fairy tale, and the jungle. We know that functionality is important, so you will also find ample storage solutions like shelves and cabinets to keep the room organized and clutter-free. Play areas with ageappropriate toys and activities that stimulate creativity and imagination are also featured, together with study areas with playful desks, comfortable chairs, and good lighting to support their learning activities. By using imagination, and involving the child in the design process, one can create a magical room that will inspire creativity, wonder, and joy in children. It’s all about creating a magical experience!',
                'type' => 'catalogue',
                'slug' => 'covet-house-kids',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Covet House Best Sellers',
                'subtitle' => 'Discover the Most Coveted Designs',
                'description' => 'Craftsmanship is probably the most successful element when creating statement interiors. Handmade objects tell stories of passion, care, and effort. The hands that create art from materials such as wood, marble, or metal carry the legacy of generations and the power and propensity to create beauty. Our collection features over 150 highly curated sideboards, consoles, cabinets, bookcases, screens, and mirrors that celebrate the art of craftsmanship though skilled work and great attention to detail. Our dedicated team of designers and craftsmen work side by side every day to launch dozens of new modern, classic, vintage and contemporary art pieces every year. This way, we make sure there is a solution for every project. Statement interiors are storytellers, and statement designs are timeless heirlooms that will only gain more significance as the years go by.',
                'type' => 'catalogue',
                'slug' => 'covet-house-best-sellers',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Coveted Magazine’s 30th Issue',
                'subtitle' => null,
                'description' => null,
                'type' => 'magazine',
                'slug' => 'coveted-30',
                'external_link' => 'https://www.circu.net/catalogues-and-ebooks/coveted-edition-magazine-thirty-edition/?utm_source=website&utm_medium=alleditorialcontent&utm_content=caffelattehome-covetedition27-pagcatalogues&utm_campaign=covetedition27?utm_source=website&utm_medium=cataloguesandbooks&utm_content=coveted-edition-magazine-thirty-edition-covethouse&utm_campaign=covetedition30',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'Dreams to Mansions',
                'subtitle' => 'Navigating Million-Dollar Homes',
                'description' => '“Dreams to Mansions: Navigating Million-Dollar Homes” is an immersive guide that transcends the ordinary realm of property, inviting you into a world of opulence and luxury. It encompasses a diverse array of design inspirations, from meticulously crafted residential and hospitality ambiances to intricately detailed children’s rooms. This extraordinary journey ventures beyond conventional boundaries, unveiling a rich tapestry of design concepts and styles that ignite creativity. Serving as a creative catalyst, we offer a meticulously curated collection and expertise, inspiring projects aimed at elevating homes and hospitality environments with detailed inspirations, be it crafting imaginative children’s spaces or enhancing overall designs. Embark with us on a transformative odyssey from ideation to realization, where “Dreams to Mansions” stands as your guiding companion, facilitating the elevation of spaces with unparalleled style and sophistication. Download this ebook and discover more!',
                'type' => 'ebook',
                'slug' => 'multi-million-dollar-homes',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Luxury Chalet Design',
                'subtitle' => 'in the Montreaux Mountains',
                'description' => 'The architecture of the chalet fully embraces the modern style. It maintains a few features known to rural and traditional chalets, especially with stone and wooden-related details yet it mainly presents a more current approach with modernized gabled roofs and an extensive outdoor space replete with luxurious particularities. We went all out decorating the exterior with its exquisite MYSA Outdoor Collection. Throughout the area, the Galea series receives plenty of focus. The Galea armchairs and sofas set the scene on one side, accompanied by the horizon-inspired Magna floor lamps and a marble center table with an in-built fire pit. On the other side, at the sunbathing section, the marvelous Galea grey chaise lounges paired with the Mayer side table bring the utmost comfort after a swim.',
                'type' => 'ebook',
                'slug' => 'luxury-chalet-design-in-the-montreaux-mountains',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Contemporary Modern',
                'subtitle' => 'An Exceptional $16 Million Penthouse In Monaco',
                'description' => 'Created in a series of luxury curated houses by Covet House, in a completely different style, this 295 m2, 8 room penthouse in Monaco focuses on functionality and contemporary modern design in neutral tones to create an effortlessly chic look. The social areas include an open- plan kitchen, dining and living area, as well as a powder room and a home office. Moreover, the penthouse features two extraordinary private areas – a sophisticated master bedroom which includes its own living area, and the magical kids quarters which include the bedroom, a play and study area, and a bathroom.',
                'type' => 'ebook',
                'slug' => 'contemporary-modern-penthouse-in-monaco',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Deluxe Apartment',
                'subtitle' => 'in the heart of the moscow',
                'description' => 'With a vision to maintain the concept as timeless as possible for this exquisite modern apartment, by employing geometrical lines and shapes that avoid transitory fashion trends. Also, this high-end project combines Art Deco elements with modern themes and fine craftsmanship, this apartment resulted in a work of art, with a soft modern approach. Designed by one of the many Covet House brands, Luxxu perfectly creates the best aesthetic for this Moscow project, incorporating elements associated with a detailed art decoration as well as items that would remind us of functional minimalism.',
                'type' => 'ebook',
                'slug' => 'deluxe-apartment',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Luxury Penthouse',
                'subtitle' => 'In The Heart Of Paris',
                'description' => 'In Paris, the city of love and the home of the iconic design is nestled a luxurious and eclectic 1450 square feet apartment. A multimillion-dollar penthouse that reflects the owner’s love for collectible design and the client’s needs to have a functional space for work and to be inspired at the same time. The luxury apartment has an open space concept that combines all the rooms through one unique style. An homage to art and cultural history, where every elegant detail of the classic architecture in this apartment features the white French wall moldings, highlighting the classical style of the French windows and by the city’s renaissance period, fill with art worthy designs and sculptures to enhance the decor bringing to life the richness of the designs.',
                'type' => 'ebook',
                'slug' => 'luxury-penthouse-in-the-heart-of-paris',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Modern Classic Elegance',
                'subtitle' => 'In Saint Petersburg',
                'description' => 'This secluded villa is another in a series of luxury houses created by Covet House with the purpose of inspiring professionals and Design lovers to new heights in this new era. The 8.5 Million, 500 m2 mansion in St. Petersburg presents elegant bespoke interiors with a modern classic touch, and a perfect balance between statement handcrafted pieces and more neutral, functional elements. The result is a very comfortable home fit for the modern luxury lifestyle.',
                'type' => 'ebook',
                'slug' => 'modern-classic-elegance-in-saint-petersburg',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Urban Nature Penthouse',
                'subtitle' => 'In Hong Kong',
                'description' => 'Hong Kong’s skyline has been regarded by many as the most astounding one all around the world, especially from the harbor or mountains. Considering such, this became the ideal location to develop our latest house project, a stunning penthouse replete with natural appeal, reminiscent of the region’s breathtaking horizons. Paying homage to Hong Kong’s architectural style, we introduced both a modern and contemporary feel to the luxury oasis.',
                'type' => 'ebook',
                'slug' => 'urban-nature-penthouse-in-hong-kong',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Opulent Modern Classic Villa',
                'subtitle' => 'in Dubai',
                'description' => 'A truly magnificent villa, located in one of the most coveted and fast-growing environmentsin the world, the grandiose Dubai. Another house in a collection of curated houses created byCovet House showcasing various styles and inspirations around the world, this time strikingin the United Arab Emirates. Set in otherworldly landscapes of the luxurious Dubai, the villawas designed by Karim Abdul Muttalib, from K. A. Interior Design in partnership with CovetHouse.',
                'type' => 'ebook',
                'slug' => 'opulent-modern-classic-villa-in-dubai',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Worth of the Top A-Listers',
                'subtitle' => 'in New York',
                'description' => 'Creating a beautiful, balanced aesthetic is quite a task, but creating a house worthy ofsome of the biggest stars on the planet, is an out-of-this-world mission. Covet House didit again, this time joining forces with Kintsugi Visual, a studio co-founded by Ivan Satria,whose artistry alongside Covet House’s luxury brands and pieces, produced a project soexclusive, so magnificent, that will surely be one of the most coveted condos in New York.',
                'type' => 'ebook',
                'slug' => 'worth-of-the-top-a-listers-in-new-york',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Premium Condo Interior',
                'subtitle' => 'in New Delhi',
                'description' => 'We present a brand-new apartment in the capital of India, New Delhi. This luxury homebecomes part of our legacy of opulent interior design projects, by presenting a uniqueatmosphere, in a singular location, with a privileged view. The enormous 452 meters high ofthis architectural wonder is replicated inside the house, where everything is sumptuous, fromthe wide spaces to the bespoke pieces.',
                'type' => 'ebook',
                'slug' => 'premium-condo-interior-in-new-delhi',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Eternal Contemporary Experience',
                'subtitle' => 'in Milan',
                'description' => 'The two master suite bedrooms apartment located at Corso Garibaldi, 65, in Milan, has 412.4m2/4439.03ft2 of contemporary classic luxury design vibe all over it. Each room tellsa particular story lived by the owner, a young lady with a particular and vibrant way of living.From the moment you step in, you will start a journey that will fulfil your senses and will makeyou want to stay.',
                'type' => 'ebook',
                'slug' => 'eternal-contemporary-experience-in-milan',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'A Modern Villa Design',
                'subtitle' => 'in Miami',
                'description' => 'This magnificent home is located in Miami and is large enough to accomodate a family of four while still allowing plenty of intimacy and privacy. Covet House defied expectations by bringing comfort and opulence to this property, transforming its decor into the absolute pinnacle of the Miami ethos.',
                'type' => 'ebook',
                'slug' => 'a-modern-villa-design-in-miami',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Contemporary Oasis',
                'subtitle' => 'inside a Modern Saint Petersburg Villa',
                'description' => 'Welcome to a home where contemporary design meets luxurious comfort. This exquisite modern villa in Russia is thoughtfully crafted to provide an exceptional living experience. From the grand entrance and elegant foyer to the sophisticated home office, every space is tailored to balance beauty and functionality.',
                'type' => 'ebook',
                'slug' => 'contemporary-oasis',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Opulence Revealed',
                'subtitle' => 'A Journey Inside a Classic DUBAI Villa',
                'description' => 'Situated in the heart of the “City of Gold,” this villa, designed by Covet House, is a celebration of modern classic design. The residence seamlessly combines the grandeur of classic style with contemporary sophistication, creating spaces that reflect both tradition and modernity. Details such as marble and boiserie evoke the splendor of classic design, while Covet House’s contemporary furniture adds a touch of innovation. The neutral color palette, with predominantly darker tones, creates a warm and luxurious atmosphere, balancing elegance and comfort. Inspired by Middle Eastern influences, the villa also features a strong presence of Western sophistication. This captivating project exemplifies how luxury can be harmoniously lived through a careful fusion of the classic and the modern.',
                'type' => 'ebook',
                'slug' => 'opulence-revealed-a-journey-inside-a-classic-dubai-villa',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'A MODERN HAVEN BY THE LAKE',
                'subtitle' => 'A SWISS VILLA BETWEEN GENEVA AND LAUSANNE',
                'description' => 'Where the stillness of the lake meets the pulse of contemporary design, this extraordinary villa offers more than just a place to live—it offers a way to feel. Set in a privileged location between Geneva and Lausanne, this architectural gem invites you to experience life surrounded by natural beauty and quiet sophistication.',
                'type' => 'ebook',
                'slug' => 'a-modern-haven-by-the-lake',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => true,
            ],
            [
                'title' => 'Covet Collection New Products',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'new-products-covet-collection',
                'external_link' => 'https://covetcollection.eu/new-products-ebooks/?utm_source=website&utm_medium=cataloguesandbookscvt&utm_content=new-products-23&utm_campaign=newproducts',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'New Products Caffe Latte',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'new-products-caffe-latte',
                'external_link' => 'https://www.caffelattehome.com/ebooks/new-products-ebook?utm_source=website&utm_medium=cataloguesandbooks&utm_content=covethouse-newproducts-23-pagcatalogues&utm_campaign=newproducts',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'New Products Circu',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'new-products-circu',
                'external_link' => 'https://www.circu.net/catalogues-and-ebooks/new-products?utm_source=website&utm_medium=cataloguesandbooks&utm_content=covethouse-newproducts-cc-pagcatalogues&utm_campaign=newproducts',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'New Products By Covet House',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'new-products-by-covet-house',
                'external_link' => 'https://covetcollection.eu/new-products-by-covet-house/?utm_source=website&utm_medium=partnersfooter-toinspire-cvt&utm_content=covethouse-newproducts-cvtc&utm_campaign=newproducts',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'THE SIGNATURE CAPSULE INSPIRATIONS DESIGN BOOK',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'the-signature-capsules-inspirations-book',
                'external_link' => 'https://covetcollection.eu/the-ultimate-inspirations-design-books/?utm_source=website&utm_medium=partnersfooter-toinspire-cvt&utm_content=covethouse-inspirationsbook-cvtc&utm_campaign=inspirationsbook',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'NEUTRAL MODERN INSPIRATIONS BOOK',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => 'neutral-modern-inspirations-book-caffe-latte',
                'external_link' => 'https://www.caffelattehome.com/ebooks/neutral-modern-inspirations/?utm_source=website&utm_medium=partnersfooter-toinspire-cvt&utm_content=covethouse-inspirationsbook-caffe-latte&utm_campaign=inspirationsbook',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => '100 LUXURY KIDS ROOMS',
                'subtitle' => null,
                'description' => null,
                'type' => 'ebook',
                'slug' => '100-luxury-kids-rooms-circu',
                'external_link' => 'https://www.circu.net/catalogues-and-ebooks/100-luxury-kids-rooms?utm_source=website&utm_medium=cataloguesandbooks&utm_content=covethouse-100-luxury-kids-rooms-cc-pagcatalogues&utm_campaign=100-luxury-kids-rooms',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'Boca do Lobo Catalogue',
                'subtitle' => null,
                'description' => null,
                'type' => 'catalogue',
                'slug' => 'boca-do-lobo-catalogue',
                'external_link' => 'https://www.bocadolobo.com/en/catalogues//?utm_source=website&utm_medium=editorialcontent&utm_content=covethouse-catalogue-bl&utm_campaign=catalogue-boca-do-lobo',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'New Show-stopping Capsules',
                'subtitle' => null,
                'description' => null,
                'type' => 'catalogue',
                'slug' => 'new-show-stopping-capsules',
                'external_link' => 'https://covetcollection.eu/new-show-stopping-capsules/?utm_source=website&utm_medium=editorialcontent&utm_content=covethouse-newcatalog-cvtc&utm_campaign=newcatalogue',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'CIRCU CATALOGUE',
                'subtitle' => null,
                'description' => null,
                'type' => 'catalogue',
                'slug' => 'circu-catalogue',
                'external_link' => 'https://www.circu.net/catalogues-and-ebooks/catalogue-circu-magical-furniture?utm_source=website&utm_medium=cataloguesandbookscc&utm_content=catalogue-circu-magical-furniture&utm_campaign=catalogue-circu-magical-furniture',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'CIRCU CATALOGUE',
                'subtitle' => null,
                'description' => null,
                'type' => 'catalogue',
                'slug' => 'circu-catalogue',
                'external_link' => 'https://www.circu.net/catalogues-and-ebooks/catalogue-circu-magical-furniture?utm_source=website&utm_medium=cataloguesandbookscc&utm_content=catalogue-circu-magical-furniture&utm_campaign=catalogue-circu-magical-furniture',
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'ANNUAL FURNITURE SALE',
                'subtitle' => 'INCREDIBLE DISCOUNTS FOR A LIMITED TIME',
                'description' => 'Elevate your projects with unique designs from Covet House, available for immediate delivery. Explore our curated selection of in-stock furniture, lighting, and accessories — and bring luxury into your spaces without the wait.',
                'type' => 'stocklist',
                'slug' => 'stocklist',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'Covet House New Catalogue',
                'subtitle' => 'COVET HOUSE NEW TOOL FOR THE ULTIMATE INSPIRATION',
                'description' => 'One book. Hundreds of designs, thousands of products. An exquisite Catalogue with more than 2000 illustrated products and 1300 inspirations. Very practical, it is divided into all product categories and technical information needed to create upcoming interior design projects. The best way to find the best solutions and ideas. All the questions about the world’s top design pieces can be answered inside this collector’s book. Download Covet House‘s new catalogue and discover more!',
                'type' => 'ebook',
                'slug' => 'covet-house-new-catalogue',
                'external_link' => null,
                'is_featured' => false,
                'has_inspirational_content' => false,
            ],
            [
                'title' => 'THE ULTIMATE INSPIRATIONS DESIGN BOOK',
                'subtitle' => 'IMAGES WORTH OF THOUSAND INSPIRATIONS',
                'description' => 'More than simple inspirations, creating a beautiful, balanced aesthetic is quite a task. With a clear vision of inspiring and delivering design to the world, Covet House created powerful ambiances, that indeed are bound to inspire and boost creativity.',
                'type' => 'ebook',
                'slug' => 'the-ultimate-inspirations-design-book',
                'external_link' => null,
                'is_featured' => true,
                'has_inspirational_content' => true,
            ],

        ];

        foreach ($catalogues as $catalogue) {
            CataloguesAndEbooks::create($catalogue);
        }
    }
}
